<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->truncate();

        $countries = array(
            array("code"=>"AU","name"=>"Австралія"),
            array("code"=>"AT","name"=>"Австрія"),
            array("code"=>"AZ","name"=>"Азербайджан"),
            array("code"=>"AX","name"=>"Аландські Острови"),
            array("code"=>"AL","name"=>"Албанія"),
            array("code"=>"DZ","name"=>"Алжир"),
            array("code"=>"AS","name"=>"Американське Самоа"),
            array("code"=>"AO","name"=>"Ангола"),
            array("code"=>"AI","name"=>"Анґілья"),
            array("code"=>"AD","name"=>"Андорра"),
            array("code"=>"AQ","name"=>"Антарктика"),
            array("code"=>"AG","name"=>"Антиґуа і Барбуда"),
            array("code"=>"AR","name"=>"Аргентина"),
            array("code"=>"AW","name"=>"Аруба"),
            array("code"=>"AF","name"=>"Афганістан"),
            array("code"=>"BS","name"=>"Багамські Острови"),
            array("code"=>"BD","name"=>"Бангладеш"),
            array("code"=>"BB","name"=>"Барбадос"),
            array("code"=>"BH","name"=>"Бахрейн"),
            array("code"=>"BZ","name"=>"Беліз"),
            array("code"=>"BE","name"=>"Бельґія"),
            array("code"=>"BJ","name"=>"Бенін"),
            array("code"=>"BM","name"=>"Бермудські Острови"),
            array("code"=>"BY","name"=>"Білорусь"),
            array("code"=>"BG","name"=>"Болгарія"),
            array("code"=>"BO","name"=>"Болівія"),
            array("code"=>"BA","name"=>"Боснія і Герцеґовина"),
            array("code"=>"BW","name"=>"Ботсвана"),
            array("code"=>"BR","name"=>"Бразілія"),
            array("code"=>"IO","name"=>"Британська територія в Індійському Океані"),
            array("code"=>"VG","name"=>"Британські Віргінські острови"),
            array("code"=>"BN","name"=>"Бруней"),
            array("code"=>"BF","name"=>"Буркіна-Фасо"),
            array("code"=>"BI","name"=>"Бурунді"),
            array("code"=>"BT","name"=>"Бутан"),
            array("code"=>"VU","name"=>"Вануату"),
            array("code"=>"VA","name"=>"Ватикан"),
            array("code"=>"GB","name"=>"Велика Британія"),
            array("code"=>"VE","name"=>"Венесуела"),
            array("code"=>"UM","name"=>"Віддалені острови США"),
            array("code"=>"VI","name"=>"Віргінські острови"),
            array("code"=>"AM","name"=>"Вірменія"),
            array("code"=>"VN","name"=>"Вʼєтнам"),
            array("code"=>"GA","name"=>"Габон"),
            array("code"=>"HT","name"=>"Гаїті"),
            array("code"=>"GM","name"=>"Гамбія"),
            array("code"=>"GH","name"=>"Гана"),
            array("code"=>"GN","name"=>"Гвінея"),
            array("code"=>"GW","name"=>"Гвінея-Бісау"),
            array("code"=>"HN","name"=>"Гондурас"),
            array("code"=>"HK","name"=>"Гонконг"),
            array("code"=>"GR","name"=>"Греція"),
            array("code"=>"GE","name"=>"Грузія"),
            array("code"=>"GY","name"=>"Ґайана"),
            array("code"=>"GP","name"=>"Ґваделупа"),
            array("code"=>"GT","name"=>"Ґватемала"),
            array("code"=>"GG","name"=>"Ґернсі"),
            array("code"=>"GI","name"=>"Ґібралтар"),
            array("code"=>"GD","name"=>"Ґренада"),
            array("code"=>"GL","name"=>"Ґренландія"),
            array("code"=>"GU","name"=>"Ґуам"),
            array("code"=>"DK","name"=>"Данія"),
            array("code"=>"JE","name"=>"Джерсі"),
            array("code"=>"DJ","name"=>"Джибуті"),
            array("code"=>"DM","name"=>"Домініка"),
            array("code"=>"DO","name"=>"Домініканська Республіка"),
            array("code"=>"EC","name"=>"Еквадор"),
            array("code"=>"GQ","name"=>"Екваторіальна Гвінея"),
            array("code"=>"ER","name"=>"Еритрея"),
            array("code"=>"SZ","name"=>"Есватіні"),
            array("code"=>"EE","name"=>"Естонія"),
            array("code"=>"ET","name"=>"Ефіопія"),
            array("code"=>"EG","name"=>"Єгипет"),
            array("code"=>"YE","name"=>"Ємен"),
            array("code"=>"ZM","name"=>"Замбія"),
            array("code"=>"EH","name"=>"Західна Сахара"),
            array("code"=>"ZW","name"=>"Зімбабве"),
            array("code"=>"IL","name"=>"Ізраїль"),
            array("code"=>"IN","name"=>"Індія"),
            array("code"=>"ID","name"=>"Індонезія"),
            array("code"=>"IQ","name"=>"Ірак"),
            array("code"=>"IR","name"=>"Іран"),
            array("code"=>"IE","name"=>"Ірландія"),
            array("code"=>"IS","name"=>"Ісландія"),
            array("code"=>"ES","name"=>"Іспанія"),
            array("code"=>"IT","name"=>"Італія"),
            array("code"=>"JO","name"=>"Йорданія"),
            array("code"=>"CV","name"=>"Кабо-Верде"),
            array("code"=>"KZ","name"=>"Казахстан"),
            array("code"=>"KY","name"=>"Кайманові Острови"),
            array("code"=>"KH","name"=>"Камбоджа"),
            array("code"=>"CM","name"=>"Камерун"),
            array("code"=>"CA","name"=>"Канада"),
            array("code"=>"QA","name"=>"Катар"),
            array("code"=>"KE","name"=>"Кенія"),
            array("code"=>"KG","name"=>"Киргизстан"),
            array("code"=>"CN","name"=>"Китай"),
            array("code"=>"CY","name"=>"Кіпр"),
            array("code"=>"KI","name"=>"Кірібаті"),
            array("code"=>"CC","name"=>"Кокосові (Кілінґ) Острови"),
            array("code"=>"CO","name"=>"Колумбія"),
            array("code"=>"KM","name"=>"Комори"),
            array("code"=>"CG","name"=>"Конго – Браззавіль"),
            array("code"=>"CD","name"=>"Конго – Кіншаса"),
            array("code"=>"CR","name"=>"Коста-Ріка"),
            array("code"=>"CI","name"=>"Кот-дʼІвуар"),
            array("code"=>"CU","name"=>"Куба"),
            array("code"=>"KW","name"=>"Кувейт"),
            array("code"=>"CW","name"=>"Кюрасао"),
            array("code"=>"LA","name"=>"Лаос"),
            array("code"=>"LV","name"=>"Латвія"),
            array("code"=>"LS","name"=>"Лесото"),
            array("code"=>"LT","name"=>"Литва"),
            array("code"=>"LR","name"=>"Ліберія"),
            array("code"=>"LB","name"=>"Ліван"),
            array("code"=>"LY","name"=>"Лівія"),
            array("code"=>"LI","name"=>"Ліхтенштейн"),
            array("code"=>"LU","name"=>"Люксембурґ"),
            array("code"=>"MR","name"=>"Мавританія"),
            array("code"=>"MU","name"=>"Маврікій"),
            array("code"=>"MG","name"=>"Мадагаскар"),
            array("code"=>"YT","name"=>"Майотта"),
            array("code"=>"MO","name"=>"Макао"),
            array("code"=>"MW","name"=>"Малаві"),
            array("code"=>"MY","name"=>"Малайзія"),
            array("code"=>"ML","name"=>"Малі"),
            array("code"=>"MV","name"=>"Мальдіви"),
            array("code"=>"MT","name"=>"Мальта"),
            array("code"=>"MA","name"=>"Марокко"),
            array("code"=>"MQ","name"=>"Мартініка"),
            array("code"=>"MH","name"=>"Маршаллові Острови"),
            array("code"=>"MX","name"=>"Мексика"),
            array("code"=>"FM","name"=>"Мікронезія"),
            array("code"=>"MZ","name"=>"Мозамбік"),
            array("code"=>"MD","name"=>"Молдова"),
            array("code"=>"MC","name"=>"Монако"),
            array("code"=>"MN","name"=>"Монголія"),
            array("code"=>"MS","name"=>"Монтсеррат"),
            array("code"=>"MM","name"=>"Мʼянма (Бірма)"),
            array("code"=>"NA","name"=>"Намібія"),
            array("code"=>"NR","name"=>"Науру"),
            array("code"=>"NP","name"=>"Непал"),
            array("code"=>"NE","name"=>"Нігер"),
            array("code"=>"NG","name"=>"Нігерія"),
            array("code"=>"NL","name"=>"Нідерланди"),
            array("code"=>"BQ","name"=>"Нідерландські Карибські острови"),
            array("code"=>"NI","name"=>"Нікараґуа"),
            array("code"=>"DE","name"=>"Німеччина"),
            array("code"=>"NU","name"=>"Ніуе"),
            array("code"=>"NZ","name"=>"Нова Зеландія"),
            array("code"=>"NC","name"=>"Нова Каледонія"),
            array("code"=>"NO","name"=>"Норвеґія"),
            array("code"=>"AE","name"=>"Обʼєднані Арабські Емірати"),
            array("code"=>"OM","name"=>"Оман"),
            array("code"=>"BV","name"=>"Острів Буве"),
            array("code"=>"IM","name"=>"Острів Мен"),
            array("code"=>"NF","name"=>"Острів Норфолк"),
            array("code"=>"CX","name"=>"Острів Різдва"),
            array("code"=>"SH","name"=>"Острів Святої Єлени"),
            array("code"=>"HM","name"=>"Острови Герд і Макдоналд"),
            array("code"=>"CK","name"=>"Острови Кука"),
            array("code"=>"PN","name"=>"Острови Піткерн"),
            array("code"=>"TC","name"=>"Острови Теркс і Кайкос"),
            array("code"=>"PK","name"=>"Пакистан"),
            array("code"=>"PW","name"=>"Палау"),
            array("code"=>"PS","name"=>"Палестинські території"),
            array("code"=>"PA","name"=>"Панама"),
            array("code"=>"PG","name"=>"Папуа-Нова Ґвінея"),
            array("code"=>"PY","name"=>"Параґвай"),
            array("code"=>"PE","name"=>"Перу"),
            array("code"=>"GS","name"=>"Південна Джорджія та Південні Сандвічеві Острови"),
            array("code"=>"KR","name"=>"Південна Корея"),
            array("code"=>"SS","name"=>"Південний Судан"),
            array("code"=>"ZA","name"=>"Південно-Африканська Республіка"),
            array("code"=>"KP","name"=>"Північна Корея"),
            array("code"=>"MK","name"=>"Північна Македонія"),
            array("code"=>"MP","name"=>"Північні Маріанські Острови"),
            array("code"=>"PL","name"=>"Польща"),
            array("code"=>"PT","name"=>"Портуґалія"),
            array("code"=>"PR","name"=>"Пуерто-Ріко"),
            array("code"=>"RE","name"=>"Реюньйон"),
            array("code"=>"RU","name"=>"Росія"),
            array("code"=>"RW","name"=>"Руанда"),
            array("code"=>"RO","name"=>"Румунія"),
            array("code"=>"SV","name"=>"Сальвадор"),
            array("code"=>"WS","name"=>"Самоа"),
            array("code"=>"SM","name"=>"Сан-Маріно"),
            array("code"=>"ST","name"=>"Сан-Томе і Прінсіпі"),
            array("code"=>"SA","name"=>"Саудівська Аравія"),
            array("code"=>"SC","name"=>"Сейшельські Острови"),
            array("code"=>"BL","name"=>"Сен-Бартельмі"),
            array("code"=>"MF","name"=>"Сен-Мартен"),
            array("code"=>"PM","name"=>"Сен-Пʼєр і Мікелон"),
            array("code"=>"SN","name"=>"Сенегал"),
            array("code"=>"VC","name"=>"Сент-Вінсент і Ґренадіни"),
            array("code"=>"KN","name"=>"Сент-Кітс і Невіс"),
            array("code"=>"LC","name"=>"Сент-Люсія"),
            array("code"=>"RS","name"=>"Сербія"),
            array("code"=>"SY","name"=>"Сирія"),
            array("code"=>"SG","name"=>"Сінгапур"),
            array("code"=>"SX","name"=>"Сінт-Мартен"),
            array("code"=>"SK","name"=>"Словаччина"),
            array("code"=>"SI","name"=>"Словенія"),
            array("code"=>"SB","name"=>"Соломонові Острови"),
            array("code"=>"SO","name"=>"Сомалі"),
            array("code"=>"US","name"=>"Сполучені Штати"),
            array("code"=>"SD","name"=>"Судан"),
            array("code"=>"SR","name"=>"Сурінам"),
            array("code"=>"SL","name"=>"Сьєрра-Леоне"),
            array("code"=>"TJ","name"=>"Таджикистан"),
            array("code"=>"TH","name"=>"Таїланд"),
            array("code"=>"TW","name"=>"Тайвань"),
            array("code"=>"TZ","name"=>"Танзанія"),
            array("code"=>"TL","name"=>"Тімор-Лешті"),
            array("code"=>"TG","name"=>"Того"),
            array("code"=>"TK","name"=>"Токелау"),
            array("code"=>"TO","name"=>"Тонґа"),
            array("code"=>"TT","name"=>"Трінідад і Тобаґо"),
            array("code"=>"TV","name"=>"Тувалу"),
            array("code"=>"TN","name"=>"Туніс"),
            array("code"=>"TR","name"=>"Туреччина"),
            array("code"=>"TM","name"=>"Туркменістан"),
            array("code"=>"UG","name"=>"Уганда"),
            array("code"=>"HU","name"=>"Угорщина"),
            array("code"=>"UZ","name"=>"Узбекистан"),
            array("code"=>"UA","name"=>"Україна"),
            array("code"=>"WF","name"=>"Уолліс і Футуна"),
            array("code"=>"UY","name"=>"Уруґвай"),
            array("code"=>"FO","name"=>"Фарерські Острови"),
            array("code"=>"FJ","name"=>"Фіджі"),
            array("code"=>"PH","name"=>"Філіппіни"),
            array("code"=>"FI","name"=>"Фінляндія"),
            array("code"=>"FK","name"=>"Фолклендські Острови"),
            array("code"=>"FR","name"=>"Франція"),
            array("code"=>"GF","name"=>"Французька Ґвіана"),
            array("code"=>"PF","name"=>"Французька Полінезія"),
            array("code"=>"TF","name"=>"Французькі Південні Території"),
            array("code"=>"HR","name"=>"Хорватія"),
            array("code"=>"CF","name"=>"Центральноафриканська Республіка"),
            array("code"=>"TD","name"=>"Чад"),
            array("code"=>"CZ","name"=>"Чехія"),
            array("code"=>"CL","name"=>"Чілі"),
            array("code"=>"ME","name"=>"Чорногорія"),
            array("code"=>"CH","name"=>"Швейцарія"),
            array("code"=>"SE","name"=>"Швеція"),
            array("code"=>"SJ","name"=>"Шпіцберген та Ян-Маєн"),
            array("code"=>"LK","name"=>"Шрі-Ланка"),
            array("code"=>"JM","name"=>"Ямайка"),
            array("code"=>"JP","name"=>"Японія")
        );

        DB::table('countries')->insert($countries);
    }
}
